// Autogenerated from Pigeon (v8.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif



private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol Splash {
  func onAuthStatusChange(isLogin: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SplashSetup {
  /// The codec used by Splash.
  /// Sets up an instance of `Splash` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: Splash?) {
    let onAuthStatusChangeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.Splash.onAuthStatusChange", binaryMessenger: binaryMessenger)
    if let api = api {
      onAuthStatusChangeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isLoginArg = args[0] as! Bool
        do {
          try api.onAuthStatusChange(isLogin: isLoginArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      onAuthStatusChangeChannel.setMessageHandler(nil)
    }
  }
}
/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class SplashInteractor {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  func getAuthStatus(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.SplashInteractor.getAuthStatus", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
}
